spring:
  application:
    name: springboot-tutorials
  thymeleaf:
    # prefix: classpath:/templates
    cache: false
    encoding: utf-8
  # 热部署, 修改类和资源时不重启服务
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java  #重启目录
      exclude: static/**  #设置classpath下 static 目录内容修改后不重启。一般设置为静态资源目录
    freemarker:
      cache: false  #页面不加载缓存，修改即时生效
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lanqiaodb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      auto-commit: true
      idle-timeout: 30000
      pool-name: TutorialsHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
mybatis:
  type-aliases-package: com.lanqiao.springboottutorials.model

#分页
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundswithcount: true
  reasonable: false
  supportMethodsArguments: true
  returnPageInfo: true
  params : count=countsql
# 开放所有的 Web endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 输出 mybatis SQL日志
logging:
  level:
    root: INFO
    com.lanqiao.springboottutorials.mapper: DEBUG
    com.lanqiao.springboottutorials.controller: DEBUG
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  # \u65E5\u5FD7\u6587\u4EF6
  file:
    name: tutorials.log

